/*
@licstart  The following is the entire license notice for the
JavaScript code in this file.

Copyright (C) 1997-2019 by Dimitri van Heesch

This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

@licend  The above is the entire license notice
for the JavaScript code in this file
*/
var menudata={children:[
{text:"Main Page",url:"index.html"},
{text:"Classes",url:"annotated.html",children:[
{text:"Class List",url:"annotated.html"},
{text:"Class Index",url:"classes.html"},
{text:"Class Hierarchy",url:"hierarchy.html"},
{text:"Class Members",url:"functions.html",children:[
{text:"All",url:"functions.html",children:[
{text:"_",url:"functions.html#index__5F"},
{text:"a",url:"functions_a.html#index_a"},
{text:"b",url:"functions_b.html#index_b"},
{text:"c",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"g",url:"functions_g.html#index_g"},
{text:"h",url:"functions_h.html#index_h"},
{text:"i",url:"functions_i.html#index_i"},
{text:"j",url:"functions_j.html#index_j"},
{text:"k",url:"functions_k.html#index_k"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"n",url:"functions_n.html#index_n"},
{text:"o",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"q",url:"functions_q.html#index_q"},
{text:"r",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"u",url:"functions_u.html#index_u"},
{text:"v",url:"functions_v.html#index_v"},
{text:"w",url:"functions_w.html#index_w"},
{text:"x",url:"functions_x.html#index_x"},
{text:"y",url:"functions_y.html#index_y"},
{text:"z",url:"functions_z.html#index_z"},
{text:"~",url:"functions_~.html#index__7E"}]},
{text:"Functions",url:"functions_func.html",children:[
{text:"_",url:"functions_func.html#index__5F"},
{text:"a",url:"functions_func_a.html#index_a"},
{text:"b",url:"functions_func_b.html#index_b"},
{text:"c",url:"functions_func_c.html#index_c"},
{text:"d",url:"functions_func_d.html#index_d"},
{text:"e",url:"functions_func_e.html#index_e"},
{text:"f",url:"functions_func_f.html#index_f"},
{text:"g",url:"functions_func_g.html#index_g"},
{text:"h",url:"functions_func_h.html#index_h"},
{text:"i",url:"functions_func_i.html#index_i"},
{text:"j",url:"functions_func_j.html#index_j"},
{text:"k",url:"functions_func_k.html#index_k"},
{text:"l",url:"functions_func_l.html#index_l"},
{text:"m",url:"functions_func_m.html#index_m"},
{text:"n",url:"functions_func_n.html#index_n"},
{text:"o",url:"functions_func_o.html#index_o"},
{text:"p",url:"functions_func_p.html#index_p"},
{text:"q",url:"functions_func_q.html#index_q"},
{text:"r",url:"functions_func_r.html#index_r"},
{text:"s",url:"functions_func_s.html#index_s"},
{text:"t",url:"functions_func_t.html#index_t"},
{text:"u",url:"functions_func_u.html#index_u"},
{text:"v",url:"functions_func_v.html#index_v"},
{text:"w",url:"functions_func_w.html#index_w"},
{text:"x",url:"functions_func_x.html#index_x"},
{text:"y",url:"functions_func_y.html#index_y"},
{text:"z",url:"functions_func_z.html#index_z"},
{text:"~",url:"functions_func_~.html#index__7E"}]},
{text:"Variables",url:"functions_vars.html",children:[
{text:"_",url:"functions_vars.html#index__5F"},
{text:"a",url:"functions_vars_a.html#index_a"},
{text:"b",url:"functions_vars_b.html#index_b"},
{text:"c",url:"functions_vars_c.html#index_c"},
{text:"d",url:"functions_vars_d.html#index_d"},
{text:"e",url:"functions_vars_e.html#index_e"},
{text:"f",url:"functions_vars_f.html#index_f"},
{text:"g",url:"functions_vars_g.html#index_g"},
{text:"h",url:"functions_vars_h.html#index_h"},
{text:"i",url:"functions_vars_i.html#index_i"},
{text:"j",url:"functions_vars_j.html#index_j"},
{text:"k",url:"functions_vars_k.html#index_k"},
{text:"l",url:"functions_vars_l.html#index_l"},
{text:"m",url:"functions_vars_m.html#index_m"},
{text:"n",url:"functions_vars_n.html#index_n"},
{text:"o",url:"functions_vars_o.html#index_o"},
{text:"p",url:"functions_vars_p.html#index_p"},
{text:"q",url:"functions_vars_q.html#index_q"},
{text:"r",url:"functions_vars_r.html#index_r"},
{text:"s",url:"functions_vars_s.html#index_s"},
{text:"t",url:"functions_vars_t.html#index_t"},
{text:"u",url:"functions_vars_u.html#index_u"},
{text:"v",url:"functions_vars_v.html#index_v"},
{text:"w",url:"functions_vars_w.html#index_w"},
{text:"x",url:"functions_vars_x.html#index_x"},
{text:"y",url:"functions_vars_y.html#index_y"},
{text:"z",url:"functions_vars_z.html#index_z"}]},
{text:"Enumerations",url:"functions_enum.html",children:[
{text:"a",url:"functions_enum.html#index_a"},
{text:"b",url:"functions_enum_b.html#index_b"},
{text:"c",url:"functions_enum_c.html#index_c"},
{text:"d",url:"functions_enum_d.html#index_d"},
{text:"e",url:"functions_enum_e.html#index_e"},
{text:"f",url:"functions_enum_f.html#index_f"},
{text:"g",url:"functions_enum_g.html#index_g"},
{text:"h",url:"functions_enum_h.html#index_h"},
{text:"i",url:"functions_enum_i.html#index_i"},
{text:"k",url:"functions_enum_k.html#index_k"},
{text:"l",url:"functions_enum_l.html#index_l"},
{text:"m",url:"functions_enum_m.html#index_m"},
{text:"n",url:"functions_enum_n.html#index_n"},
{text:"o",url:"functions_enum_o.html#index_o"},
{text:"p",url:"functions_enum_p.html#index_p"},
{text:"q",url:"functions_enum_q.html#index_q"},
{text:"r",url:"functions_enum_r.html#index_r"},
{text:"s",url:"functions_enum_s.html#index_s"},
{text:"t",url:"functions_enum_t.html#index_t"},
{text:"u",url:"functions_enum_u.html#index_u"},
{text:"v",url:"functions_enum_v.html#index_v"},
{text:"w",url:"functions_enum_w.html#index_w"}]},
{text:"Properties",url:"functions_prop.html",children:[
{text:"a",url:"functions_prop.html#index_a"},
{text:"b",url:"functions_prop_b.html#index_b"},
{text:"c",url:"functions_prop_c.html#index_c"},
{text:"d",url:"functions_prop_d.html#index_d"},
{text:"e",url:"functions_prop_e.html#index_e"},
{text:"f",url:"functions_prop_f.html#index_f"},
{text:"g",url:"functions_prop_g.html#index_g"},
{text:"h",url:"functions_prop_h.html#index_h"},
{text:"i",url:"functions_prop_i.html#index_i"},
{text:"j",url:"functions_prop_j.html#index_j"},
{text:"k",url:"functions_prop_k.html#index_k"},
{text:"l",url:"functions_prop_l.html#index_l"},
{text:"m",url:"functions_prop_m.html#index_m"},
{text:"n",url:"functions_prop_n.html#index_n"},
{text:"o",url:"functions_prop_o.html#index_o"},
{text:"p",url:"functions_prop_p.html#index_p"},
{text:"q",url:"functions_prop_q.html#index_q"},
{text:"r",url:"functions_prop_r.html#index_r"},
{text:"s",url:"functions_prop_s.html#index_s"},
{text:"t",url:"functions_prop_t.html#index_t"},
{text:"u",url:"functions_prop_u.html#index_u"},
{text:"v",url:"functions_prop_v.html#index_v"},
{text:"w",url:"functions_prop_w.html#index_w"},
{text:"x",url:"functions_prop_x.html#index_x"},
{text:"y",url:"functions_prop_y.html#index_y"},
{text:"z",url:"functions_prop_z.html#index_z"}]},
{text:"Events",url:"functions_evnt.html",children:[
{text:"a",url:"functions_evnt.html#index_a"},
{text:"b",url:"functions_evnt.html#index_b"},
{text:"c",url:"functions_evnt.html#index_c"},
{text:"d",url:"functions_evnt.html#index_d"},
{text:"e",url:"functions_evnt.html#index_e"},
{text:"f",url:"functions_evnt.html#index_f"},
{text:"g",url:"functions_evnt.html#index_g"},
{text:"h",url:"functions_evnt.html#index_h"},
{text:"i",url:"functions_evnt.html#index_i"},
{text:"k",url:"functions_evnt.html#index_k"},
{text:"l",url:"functions_evnt.html#index_l"},
{text:"m",url:"functions_evnt.html#index_m"},
{text:"o",url:"functions_evnt.html#index_o"},
{text:"p",url:"functions_evnt.html#index_p"},
{text:"r",url:"functions_evnt.html#index_r"},
{text:"s",url:"functions_evnt.html#index_s"},
{text:"t",url:"functions_evnt.html#index_t"},
{text:"v",url:"functions_evnt.html#index_v"},
{text:"z",url:"functions_evnt.html#index_z"}]}]}]},
{text:"Files",url:"files.html",children:[
{text:"File List",url:"files.html"},
{text:"File Members",url:"globals.html",children:[
{text:"All",url:"globals.html",children:[
{text:"a",url:"globals.html#index_a"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"f",url:"globals.html#index_f"},
{text:"g",url:"globals.html#index_g"},
{text:"h",url:"globals.html#index_h"},
{text:"i",url:"globals.html#index_i"},
{text:"k",url:"globals.html#index_k"},
{text:"m",url:"globals.html#index_m"},
{text:"o",url:"globals.html#index_o"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"t",url:"globals.html#index_t"},
{text:"v",url:"globals.html#index_v"},
{text:"w",url:"globals.html#index_w"}]},
{text:"Functions",url:"globals_func.html"},
{text:"Enumerations",url:"globals_enum.html",children:[
{text:"a",url:"globals_enum.html#index_a"},
{text:"b",url:"globals_enum.html#index_b"},
{text:"c",url:"globals_enum.html#index_c"},
{text:"d",url:"globals_enum.html#index_d"},
{text:"e",url:"globals_enum.html#index_e"},
{text:"f",url:"globals_enum.html#index_f"},
{text:"g",url:"globals_enum.html#index_g"},
{text:"h",url:"globals_enum.html#index_h"},
{text:"i",url:"globals_enum.html#index_i"},
{text:"m",url:"globals_enum.html#index_m"},
{text:"o",url:"globals_enum.html#index_o"},
{text:"p",url:"globals_enum.html#index_p"},
{text:"r",url:"globals_enum.html#index_r"},
{text:"t",url:"globals_enum.html#index_t"},
{text:"v",url:"globals_enum.html#index_v"},
{text:"w",url:"globals_enum.html#index_w"}]}]}]}]}
